"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { cases } from "@/data/site";
import { afterSelectionFaqs, executionServices, executionStages, firstChecks, industryRecommendations, packages, problems, processSteps, solutionAreas } from "@/data/after-selection";
import { submitConsultation } from "@/lib/contact";
import { trackAfterSelectionEvent } from "@/lib/analytics";

const allServices=["전략","브랜딩","홈페이지","랜딩페이지","네이버 블로그","스마트플레이스","SNS","카드뉴스","숏폼","광고","판로","AEO·GEO","결과보고 자료","잘 모르겠습니다."];
const deliverables=[["전략",["상담 내용 정리","마케팅 실행안","콘텐츠 방향","일정표"]],["디자인·제작",["홈페이지 URL","최종 이미지","카드뉴스·영상","상세페이지·배너"]],["운영",["발행 URL","게시물 목록","광고 소재·집행 화면","운영 내역"]],["보고",["산출물 목록","실행 내역","주요 화면 캡처","URL·결과보고 참고자료"]]] as const;
const reasons=[["콘텐츠부터 고객 유입까지","검색, SNS, 광고와 문의 동선을 연결합니다."],["여러 항목을 한 팀에서","홈페이지, 블로그, SNS와 광고를 하나의 전략으로 관리합니다."],["AI 기반 빠른 실행","기획, 제작, 수정과 콘텐츠 확장을 효율적으로 진행합니다."],["AEO·GEO까지 고려","AI 검색에서도 이해하기 쉬운 정보 구조를 설계합니다."],["산출물과 보고자료","제작물, URL과 보고 참고자료를 과정에서 정리합니다."],["교육과 대행의 결합","직접 운영할 영역과 맡길 영역을 구분해드립니다."]] as const;

function Heading({eyebrow,title,description}:{eyebrow:string;title:string;description?:string}){return <div className="section-heading centered"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>}
function QuoteLink({children,location,className="button button-coral"}:{children:React.ReactNode;location:string;className?:string}){return <a className={className} href="#quote" onClick={()=>trackAfterSelectionEvent("after_selection_cta_click",{cta_location:location})}>{children}</a>}

function QuoteForm({selected,setSelected,quoteRef}:{selected:string[];setSelected:(x:string[])=>void;quoteRef:React.RefObject<HTMLElement|null>}){
 const [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle"); const [started,setStarted]=useState(false);
 const toggle=(item:string)=>setSelected(selected.includes(item)?selected.filter(x=>x!==item):[...selected,item]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(state==="sending"||state==="success")return;const form=e.currentTarget;if(!form.reportValidity())return;setState("sending");const f=new FormData(form);const value=(n:string)=>String(f.get(n)||"");const payload:Record<string,string|string[]|boolean>={submittedAt:new Date().toISOString(),inquiryType:"선정 후 실행 상담",source:"after-selection",pageUrl:location.href,referrer:document.referrer,name:value("name"),company:value("company"),phone:value("phone"),email:value("email"),region:value("region"),industry:value("industry"),selectedProgram:value("selectedProgram"),organization:value("organization"),currentStage:value("currentStage"),supportBudget:value("supportBudget"),marketingBudget:value("marketingBudget"),selfPayment:value("selfPayment"),agreementStart:value("agreementStart"),executionDeadline:value("executionDeadline"),selectedServices:selected,consultationMethod:value("consultationMethod"),preferredTime:value("preferredTime"),message:value("message"),referenceUrl:value("referenceUrl"),privacyConsent:true,marketingConsent:f.get("marketingConsent")==="동의",status:"신규 문의",userAgent:navigator.userAgent};trackAfterSelectionEvent("quote_form_submit",{current_stage:value("currentStage"),selected_program:value("selectedProgram"),industry:value("industry"),selected_services:selected.join("|"),budget_range:value("marketingBudget")});try{await submitConsultation(payload);setState("success");trackAfterSelectionEvent("quote_form_success",{selected_services:selected.join("|")})}catch{setState("error");trackAfterSelectionEvent("quote_form_error")}}
 if(state==="success")return <section ref={quoteRef} id="quote" className="after-quote section"><div className="shell"><div className="after-success" role="status"><span>✓</span><h2>선정 후 실행 상담이 접수되었습니다.</h2><p>협약 내용과 실행 일정을 확인한 후 연락드리겠습니다.</p></div></div></section>;
 return <section ref={quoteRef} id="quote" className="after-quote section"><div className="shell quote-layout"><aside><span className="eyebrow light">맞춤 견적 요청</span><h2>지원사업명과<br/>실행 마감일을 알려주세요</h2><p>협약 내용, 실행 범위와 일정을 확인한 후 진행 가능한 항목과 맞춤 견적을 안내해드립니다.</p><ul><li>협약·예산 항목 확인</li><li>우선 실행 범위 정리</li><li>산출물·일정·견적 안내</li></ul></aside><form className="after-form" onSubmit={submit} onFocus={()=>{if(!started){setStarted(true);trackAfterSelectionEvent("quote_form_start")}}} noValidate><div className="after-form-grid">
  <label>이름 <b>*</b><input name="name" required autoComplete="name"/></label><label>업체명 <b>*</b><input name="company" required autoComplete="organization"/></label><label>연락처 <b>*</b><input name="phone" required inputMode="tel" autoComplete="tel"/></label><label>이메일<input name="email" type="email" autoComplete="email"/></label><label>업종 <b>*</b><input name="industry" required placeholder="예: 식품 제조"/></label><label>지역<input name="region" placeholder="예: 서울"/></label><label>선정된 지원사업 <b>*</b><input name="selectedProgram" required placeholder="예: 희망리턴패키지"/></label><label>주관기관<input name="organization"/></label>
  <label>현재 진행 단계 <b>*</b><select name="currentStage" required defaultValue=""><option value="" disabled>선택해주세요</option>{["선정 통보","협약 준비","협약 완료","실행업체 탐색","실행 중","결과보고 준비"].map(x=><option key={x}>{x}</option>)}</select></label><label>실행 마감일 <b>*</b><input name="executionDeadline" type="date" required/></label><label>총 지원 규모<input name="supportBudget"/></label><label>마케팅 집행 가능 예산<select name="marketingBudget" defaultValue=""><option value="">선택해주세요</option>{["500만원 미만","500만~1,000만원","1,000만~3,000만원","3,000만~5,000만원","5,000만원 이상","아직 확인 중"].map(x=><option key={x}>{x}</option>)}</select></label><label>자부담 여부<select name="selfPayment" defaultValue=""><option value="">선택해주세요</option><option>있음</option><option>없음</option><option>확인 중</option></select></label><label>협약 시작일<input name="agreementStart" type="date"/></label><label>희망 상담 방식<select name="consultationMethod" defaultValue=""><option value="">선택해주세요</option>{["전화","문자","카카오톡","줌","방문 상담"].map(x=><option key={x}>{x}</option>)}</select></label><label>연락 가능 시간<input name="preferredTime" placeholder="예: 평일 오후 2~5시"/></label>
 </div><fieldset><legend>필요한 서비스 <b>*</b></legend><div className="after-check-grid">{allServices.map(item=><label key={item} className={selected.includes(item)?"selected":""}><input type="checkbox" checked={selected.includes(item)} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</div>{selected.length>0&&<p className="selection-summary">선택됨: {selected.join(" · ")}</p>}</fieldset><label className="full-label">현재 고민<textarea name="message" rows={5} placeholder="현재 상황, 필요한 실행과 마감 관련 고민을 알려주세요."/></label><label className="full-label">참고 링크<input name="referenceUrl" type="url" placeholder="https://"/></label>
 <div className="file-placeholder"><strong>자료 첨부 준비 영역</strong><p>선정 확인서, 협약서, 사업계획서, 예산표, 실행 지침과 참고자료를 추후 안전한 저장소 연결 후 첨부할 수 있습니다.</p><small>예정 형식: PDF, DOCX, HWP, XLSX, JPG, PNG · 파일 크기 기준은 저장소 연결 시 안내</small><button type="button" disabled>파일 첨부 준비 중</button></div><label className="privacy-row"><input type="checkbox" required/><span><Link href="/privacy" target="_blank">개인정보 수집 및 이용</Link>에 동의합니다. <b>*</b></span></label><label className="privacy-row optional"><input type="checkbox" name="marketingConsent" value="동의"/><span>마케팅 정보 수신에 동의합니다. (선택)</span></label>{state==="error"&&<p className="form-error" role="alert">제출하지 못했습니다. 입력 내용을 확인하고 다시 시도해주세요.</p>}<button className="button button-coral after-submit" type="submit" disabled={state==="sending"}>{state==="sending"?"제출 중…":"선정 후 실행 상담 신청 →"}</button><p className="form-footnote">접수 내용을 확인한 후 영업일 기준 1일 이내 연락드립니다.</p></form></div></section>
}

export function AfterSelectionPage(){
 const [stage,setStage]=useState("");const [selected,setSelected]=useState<string[]>([]);const [industry,setIndustry]=useState(Object.keys(industryRecommendations)[0]);const [sticky,setSticky]=useState(true);const quoteRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{trackAfterSelectionEvent("after_selection_view")},[]);useEffect(()=>{const n=quoteRef.current;if(!n)return;const o=new IntersectionObserver(([e])=>setSticky(!e.isIntersecting),{threshold:.08});o.observe(n);return()=>o.disconnect()},[]);
 const addServices=(items:readonly string[],packageType?:string)=>{const next=Array.from(new Set([...selected,...items]));setSelected(next);if(packageType)trackAfterSelectionEvent("package_select",{package_type:packageType,selected_services:next.join("|")})};
 return <div className="after-page">
 <section className="after-hero"><div className="shell after-hero-grid"><div className="after-hero-copy"><span className="eyebrow light">정부지원사업 선정 후 마케팅 실행</span><h1>정부지원사업에 선정되셨나요?<br/>이제 <em>계획을 성과로</em><br/>바꿀 차례입니다</h1><p>사업계획서에 작성한 홈페이지, 콘텐츠, 광고와 판로개척을 실제 고객 유입과 매출로 연결할 실행 파트너가 필요합니다.</p><p className="after-hero-sub">거상마케팅센터는 지원사업의 목적과 집행 기준을 확인한 뒤 기획, 제작, 운영, 산출물과 결과보고 자료까지 함께 관리합니다.</p><div className="button-row"><QuoteLink location="hero">선정 후 실행 상담받기 →</QuoteLink><QuoteLink location="hero_quote" className="button button-dark-outline">맞춤 견적 요청하기</QuoteLink></div><a className="hero-text-link" href="#services-select">필요한 서비스 먼저 확인하기 ↓</a><small>실제 진행 가능 항목은 선정된 사업의 협약서, 예산 편성 내용과 집행 기준을 확인한 후 결정됩니다.</small></div><div className="after-hero-visual"><Image src="/images/hero-korean-consulting-v2.png" alt="한국인 소상공인 대표와 마케팅 전문가가 노트북으로 실행 계획을 검토하는 모습" fill priority sizes="(max-width:1024px) 100vw,48vw"/><div className="hero-status-card"><span>현재 실행 단계</span><strong>협약 확인 → 전략 → 제작 → 운영 → 결과보고</strong></div><div className="hero-fast-card"><span>빠른 상담</span><strong>지원사업명과 실행 마감일을 알려주세요.</strong></div></div></div></section>
 <section className="urgent-stage"><div className="shell"><div><span>빠른 실행 진단</span><h2>현재 어느 단계이신가요?</h2></div><div className="stage-options">{executionStages.map(([label])=><button key={label} className={stage===label?"selected":""} onClick={()=>{setStage(label);trackAfterSelectionEvent("urgent_stage_select",{current_stage:label})}}>{label}</button>)}</div><button className="button button-primary" disabled={!stage} onClick={()=>{const item=executionStages.find(x=>x[0]===stage);if(item)document.getElementById(item[1])?.scrollIntoView()}}>현재 단계에 맞는 실행안 보기 →</button></div></section>
 <section id="first-check" className="section"><div className="shell"><Heading eyebrow="선정 직후 체크" title="선정 통보를 받았다면 계약보다 먼저 이것부터 확인하세요" description="지원사업은 무엇을 만들 것인가만큼 언제, 어떤 기준으로 집행할 것인가가 중요합니다."/><div className="first-check-grid">{firstChecks.map((c,i)=><article key={c[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{c[0]}</h3><ul>{c.slice(1).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
 <section className="section section-soft"><div className="shell"><Heading eyebrow="실행이 막히는 순간" title="선정됐지만 실행이 막히는 이유"/><div className="problem-grid">{problems.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></article>)}</div><div className="after-emphasis"><p>결과물 하나를 납품하는 데서 끝내지 않고, 고객이 발견하고 신뢰하고 문의하는 흐름까지 설계합니다.</p><QuoteLink location="problem">내 상황 상담하기 →</QuoteLink></div></div></section>
 <section className="section"><div className="shell"><Heading eyebrow="통합 실행팀" title="기획부터 실행과 보고까지 한 팀에서 관리합니다" description="업체는 하나, 실행 흐름도 하나, 산출물과 보고 자료까지 일관되게 관리합니다."/><div className="solution-grid">{solutionAreas.map(([t,d,items],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p><div>{items.map(x=><b key={x}>{x}</b>)}</div></article>)}</div></div></section>
 <section id="process" className="section section-soft"><div className="shell"><Heading eyebrow="전체 실행 프로세스" title="선정 후 마케팅 실행 프로세스" description="전체 일정은 실행 항목, 제작 범위와 사업 마감일을 확인한 뒤 안내합니다."/><ol className="execution-timeline">{processSteps.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3><p><b>고객 준비</b>{i<4?"협약·목표·기한 정보":"검수와 승인 의견"}</p><p><b>센터 진행</b>{i<4?"범위·일정·산출물 설계":"제작·운영·자료 정리"}</p><small>대표 산출물 · {i<4?"검토표·실행안":"제작물·실행 기록"}</small></li>)}</ol></div></section>
 <section id="services-select" className="section"><div className="shell"><Heading eyebrow="서비스 선택" title="어떤 실행이 필요하신가요?" description="여러 서비스를 선택하면 아래 맞춤 견적 요청에 자동으로 반영됩니다."/><div className="execution-service-grid">{executionServices.map((s,i)=>{const active=s.items.some(x=>selected.includes(x));return <article key={s.title} className={active?"selected":""}><div className="service-card-head"><span>{String(i+1).padStart(2,"0")}</span><h3>{s.title}</h3></div><dl><div><dt>해결하는 문제</dt><dd>{s.problem}</dd></div><div><dt>제공 결과물</dt><dd>{s.result}</dd></div><div><dt>적합한 고객</dt><dd>{s.fit}</dd></div></dl><button onClick={()=>{addServices(s.items);trackAfterSelectionEvent("execution_service_select",{selected_services:s.items.join("|")})}}>{active?"선택됨 ✓":"이 서비스 선택하기"}</button><QuoteLink location={`service_${i}`} className="service-consult-link">상담 요청 →</QuoteLink></article>})}</div><div className="selection-dock"><span>{selected.length?`${selected.length}개 서비스가 견적 요청에 반영됩니다.`:"필요한 서비스를 복수로 선택할 수 있습니다."}</span><QuoteLink location="service_selection">선택 내용으로 견적 요청 →</QuoteLink></div></div></section>
 <section className="section section-soft"><div className="shell"><Heading eyebrow="목적별 실행 패키지" title="목적에 맞는 실행 조합을 선택하세요" description="확정 가격 상품이 아닌 상담을 위한 서비스 조합입니다."/><div className="after-package-grid">{packages.map(p=><article key={p.key} className={"featured" in p&&p.featured?"featured":""}>{"featured" in p&&p.featured&&<b className="package-badge">가장 많이 상담하는 조합</b>}<span>PACKAGE</span><h3>{p.title}</h3><p>{p.fit}</p><ul>{p.items.map(x=><li key={x}>{x}</li>)}</ul><button className="button button-primary" onClick={()=>{addServices(p.items,p.key);document.getElementById("quote")?.scrollIntoView()}}>{p.cta} →</button></article>)}</div></div></section>
 <section className="section"><div className="shell"><Heading eyebrow="업종별 추천" title="업종에 따라 필요한 마케팅이 다릅니다"/><div className="industry-tabs" role="tablist">{Object.keys(industryRecommendations).map(x=><button role="tab" aria-selected={industry===x} key={x} className={industry===x?"selected":""} onClick={()=>setIndustry(x)}>{x}</button>)}</div><div className="industry-result"><div><span>추천 업종</span><h3>{industry}</h3><p>현재 고객 접점과 사업 목표를 기준으로 먼저 검토할 실행 조합입니다.</p></div><div>{industryRecommendations[industry].map(x=><span key={x}>{x}</span>)}</div><button onClick={()=>addServices(industryRecommendations[industry])}>추천 조합 선택하기 →</button></div><p className="after-note">업종별 추천은 참고용이며 실제 실행안은 목표와 집행 기준 확인 후 결정됩니다.</p></div></section>
 <section className="section section-soft"><div className="shell"><Heading eyebrow="제공 산출물" title="완료 후 어떤 자료를 받을 수 있나요?"/><div className="deliverable-grid">{deliverables.map(([t,items])=><article key={t}><h3>{t}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><p className="after-note">실제 제공 파일과 원본 제공 범위는 계약 내용에 따라 달라질 수 있습니다.</p></div></section>
 <section id="reporting" className="section reporting-section"><div className="shell reporting-grid"><div><span className="eyebrow light">증빙·결과보고 지원</span><h2>실행이 끝나기 전에<br/>증빙과 결과보고를 준비합니다</h2><p>실행 과정에서 필요한 자료를 함께 정리해 마감 직전의 누락을 줄입니다.</p></div><div className="report-scope"><article><span>거상마케팅센터 제공 가능</span><ul>{["견적서·계약서·세금계산서","제작·운영 산출물","결과물 URL·이미지·영상","실행 내역·결과보고 참고자료"].map(x=><li key={x}>{x}</li>)}</ul></article><article><span>고객·주관기관 확인 영역</span><ul>{["협약서·집행 승인","지원금 지급·자부담","정산 기준·공식 양식","주관기관 제출·최종 승인"].map(x=><li key={x}>{x}</li>)}</ul></article></div><strong className="report-warning">최종 정산과 결과보고 승인 여부는 각 지원사업의 주관기관 판단과 기준에 따릅니다.</strong></div></section>
 <section className="section"><div className="shell"><Heading eyebrow="프로젝트 사례" title="정부지원사업 선정 후 실행 사례" description="허위 성과 수치 없이 고객 상황과 설계할 실행 범위를 중심으로 안내합니다."/><div className="case-grid">{cases.slice(0,3).map((x,i)=><article className="case-card" key={x.slug}><div className={`case-visual case-visual-${i+1}`}><span>{x.industry}</span><b>{String(i+1).padStart(2,"0")}</b></div><div className="case-card-body"><div className="case-top"><span>{x.program}</span><b>{x.status}</b></div><h3>{x.title}</h3><dl><div><dt>선정 후 상황</dt><dd>{x.problem}</dd></div><div><dt>실행 항목</dt><dd>{x.execution.join(" · ")}</dd></div><div><dt>제공 산출물</dt><dd>{x.deliverables.join(" · ")}</dd></div></dl><Link href={`/cases/${x.slug}`} onClick={()=>trackAfterSelectionEvent("case_view",{cta_location:x.slug})}>상세보기 →</Link></div></article>)}</div><div className="center-action"><QuoteLink location="cases">비슷한 상황 상담하기 →</QuoteLink></div></div></section>
 <section className="section section-soft"><div className="shell"><Heading eyebrow="선택 이유" title="제작업체가 아니라 마케팅 실행팀이 필요합니다"/><div className="reason-grid">{reasons.map(([t,d],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="section"><div className="shell"><Heading eyebrow="투명한 서비스 범위" title="직접 수행과 전문가 연결 범위를 명확히 안내합니다"/><div className="scope-grid"><article><span>직접 수행</span><h3>마케팅 실행</h3><p>전략, 홈페이지, 랜딩페이지, 블로그, 스마트플레이스, SNS, 콘텐츠, 숏폼, 광고, AEO·GEO와 산출물 정리</p></article><article><span>연결 가능</span><h3>외부 전문가</h3><p>사업계획서 전문 검토, 세무·회계, 법률·행정, 특허, 수출과 정산 전문 업무</p></article><article className="scope-no"><span>보장하지 않음</span><h3>정부기관의 판단 영역</h3><p>선정, 지원금 지급, 정산 승인, 매출, 특정 검색 순위와 주관기관의 최종 판단</p></article></div></div></section>
 <QuoteForm selected={selected} setSelected={setSelected} quoteRef={quoteRef}/>
 <section id="faq" className="section"><div className="shell"><Heading eyebrow="자주 묻는 질문" title="선정 후 실행, 무엇이 궁금하신가요?"/><div className="faq-list">{afterSelectionFaqs.map(x=><details key={x.q}><summary>{x.q}<span>＋</span></summary><p>{x.a}</p></details>)}</div></div></section>
 <section className="after-final"><div className="shell"><span className="eyebrow light">실행 일정 확인</span><h2>지원사업 실행 기간은 기다려주지 않습니다</h2><h3>선정 통보를 받았다면 지금 실행 일정부터 확인하세요.</h3><p>지원사업명, 필요한 서비스와 마감일을 알려주시면 진행 가능한 범위와 우선순위부터 안내해드립니다.</p><div className="button-row"><QuoteLink location="final">선정 후 실행 상담 →</QuoteLink><QuoteLink location="final_quote" className="button button-white">맞춤 견적 요청</QuoteLink><a className="button button-dark-outline" href="#services-select">서비스 조합 확인</a></div><small>상담만으로 계약이 확정되지 않으며, 실제 진행 여부는 협약과 집행 기준, 일정과 제작 범위를 검토한 후 결정됩니다.</small></div></section>
 {sticky&&<div className="after-sticky"><QuoteLink location="sticky">맞춤 견적 요청 →</QuoteLink></div>}<nav className="after-related" aria-label="관련 페이지"><div className="shell">{[["지원사업","/programs"],["희망리턴패키지","/hope-return"],["무료 자가진단","/diagnosis"],["서비스","/services"],["실행 사례","/cases"],["전문가","/experts"],["자료실","/insights"],["개인정보처리방침","/privacy"]].map(([l,h])=><Link key={h} href={h}>{l} →</Link>)}</div></nav>
 </div>
}
