"use client";

import Image from "next/image";
import Link from "next/link";
import { ContactWizard } from "@/components/ContactWizard";
import { contactFaqs, inquiryTypes } from "@/data/contact";
import { trackContactEvent } from "@/lib/analytics";

const related=(label:string,href:string,location:string)=><Link href={href} onClick={()=>trackContactEvent("contact_related_page_click",{source_page:"/contact",cta_location:location})}>{label} →</Link>;

export function ContactLandingPage(){return <div className="contact-landing">
 <section className="contact-hero"><div className="shell contact-hero-grid"><div><span className="eyebrow">정부지원사업·마케팅 1:1 상담</span><h1>현재 상황을 알려주시면<br/><em>다음 실행부터</em> 정리해드립니다</h1><p>지원사업을 처음 알아보는 단계부터 선정 이후 홈페이지·콘텐츠·광고와 결과보고까지 현재 상황에 맞는 상담을 신청할 수 있습니다.</p><div className="contact-trust">{["상담 신청 무료","전국 비대면 상담 가능","영업일 기준 1일 이내 확인","계약 전 충분한 범위 협의","개인정보 안전 관리"].map(x=><span key={x}>✓ {x}</span>)}</div><div className="button-row"><a className="button button-coral" href="#contact-types">상담 유형 선택하기 →</a><Link className="button button-ghost" href="/diagnosis">먼저 자가진단</Link></div><small>상담 신청만으로 계약이 체결되지 않으며, 지원사업 선정, 지원금 지급과 매출 성과를 보장하지 않습니다.</small></div><div className="contact-hero-visual"><Image src="/images/hero-korean-consulting-v2.png" alt="노트북과 사업 자료를 함께 검토하는 한국인 소상공인과 마케팅 전문가" fill priority sizes="(max-width: 768px) 100vw, 45vw"/><aside><span>상담 접수 후 진행</span><ol><li>문의 내용 확인</li><li>담당자 연락</li><li>상담 및 자료 검토</li><li>실행 범위·견적 안내</li></ol></aside></div></div></section>
 <section className="section contact-types" id="contact-types"><div className="shell"><div className="section-heading centered"><span className="eyebrow">상담 유형 선택</span><h2>어떤 상담이 필요하신가요?</h2><p>가장 가까운 유형을 선택하면 관련 질문과 서비스 선택지가 먼저 표시됩니다.</p></div><div className="contact-type-grid">{inquiryTypes.map((type,index)=><Link key={type.id} href={`/contact?inquiryType=${type.id}#contact-form`}><span>{String(index+1).padStart(2,"0")}</span><h3>{type.title}</h3><p>{type.description}</p><div>{type.areas.map(x=><small key={x}>{x}</small>)}</div><b>이 상담 선택 →</b></Link>)}</div></div></section>
 <section className="section section-soft contact-process"><div className="shell"><div className="section-heading centered"><span className="eyebrow">상담 진행 절차</span><h2>상담 신청 후 이렇게 진행됩니다</h2></div><ol>{[["01","상담 신청","현재 상태와 필요한 도움을 입력합니다."],["02","접수 내용 확인","지원사업 단계와 필요한 전문가·서비스를 확인합니다."],["03","담당자 연락","영업일 기준 1일 이내 기본 내용을 확인합니다."],["04","상담 및 자료 검토","필요한 경우 협약서, 사업계획서와 예산표를 함께 검토합니다."],["05","실행 범위·견적 안내","진행 가능한 범위, 일정과 견적을 안내합니다."]].map(([n,t,d])=><li key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></li>)}</ol><p className="process-note">상담 내용과 프로젝트 상황에 따라 추가 자료를 요청할 수 있습니다.</p></div></section>
 <section className="section contact-form-section" id="contact-form"><div className="shell"><div className="section-heading centered"><span className="eyebrow">무료 1:1 상담 신청</span><h2>3단계로 필요한 내용만 알려주세요</h2><p>필수 정보는 최소화하고, 선정 고객에게만 협약·예산 관련 질문을 추가로 표시합니다.</p></div><ContactWizard/></div></section>
 <section className="section section-soft contact-preparation"><div className="shell"><div className="section-heading"><span className="eyebrow">상담 전 준비자료</span><h2>다음 자료가 있으면 상담이 더 빨라집니다</h2><p>자료가 없어도 상담 신청은 가능합니다.</p></div><div className="prep-grid">{[["선정 전 고객",["관심 있는 공고","사업자등록 정보","업종과 지역","현재 사업 현황","준비 중인 사업계획"]],["선정 후 고객",["선정된 지원사업명","협약서","사업계획서","예산표","실행 마감일","필요한 마케팅 항목"]],["마케팅 일반 고객",["현재 홈페이지","블로그·SNS","상품·서비스 소개","주요 고객","현재 마케팅 고민","예상 일정과 예산"]]].map(([title,items])=><article key={String(title)}><span>{title}</span><ul>{(items as string[]).map(x=><li key={x}>✓ {x}</li>)}</ul></article>)}</div><div className="secure-files"><b>민감한 서류 전달 안내</b><p>현재 상담 폼은 파일을 저장하지 않습니다. 상담 접수 후 필요한 경우 담당자가 안전한 별도 전달 방법을 안내합니다.</p></div></div></section>
 <section className="section contact-scope"><div className="shell"><div className="section-heading centered"><span className="eyebrow">상담 가능 범위</span><h2>직접 수행과 전문가 연결을 구분해 안내합니다</h2></div><div className="scope-columns"><article className="direct"><span>거상마케팅센터 직접 수행</span><h3>마케팅 전략과 실행</h3><div>{["마케팅 전략","브랜드 콘셉트","홈페이지·랜딩페이지","상세페이지","네이버 블로그","스마트플레이스","SNS·카드뉴스·숏폼","광고·체험단","인플루언서·공동구매","AEO·GEO","산출물·결과보고 자료"].map(x=><b key={x}>✓ {x}</b>)}</div></article><article><span>외부 전문가 연결 가능</span><h3>전문 자격과 검토 영역</h3><div>{["지원사업 자격 검토","사업계획서","세무·회계","법률·행정","폐업·재창업","특허","수출"].map(x=><b key={x}>＋ {x}</b>)}</div></article><article className="not-provided"><span>제공하거나 보장하지 않음</span><h3>최종 판단과 성과 보장</h3><div>{["정부지원사업 선정·지원금 지급","정산 승인","매출·광고 성과","검색 순위","정부기관을 대신한 최종 판단"].map(x=><b key={x}>— {x}</b>)}</div></article></div></div></section>
 <section className="section section-soft contact-after"><div className="shell"><div><span className="eyebrow">상담 후 진행 방식</span><h2>자료 검토 후 범위와 견적을 투명하게 안내합니다</h2><p>접수 내용만으로 계약을 확정하지 않습니다. 필요한 자료와 목표, 예산, 기한을 확인한 뒤 직접 수행과 외부 전문가 연결 범위를 구분합니다.</p></div><div className="after-steps"><span><b>01</b>요청 범위 확인</span><span><b>02</b>필요 자료 검토</span><span><b>03</b>담당 영역 구분</span><span><b>04</b>일정·산출물 제안</span><span><b>05</b>견적·계약 협의</span></div></div></section>
 <section className="section contact-privacy-info"><div className="shell privacy-panel"><div><span className="eyebrow">개인정보 안내</span><h2>상담에 필요한 정보만 수집합니다</h2><p>필수 동의와 마케팅 정보 수신 선택 동의를 분리했습니다. 선택 동의를 하지 않아도 상담 신청이 가능합니다.</p></div><ul><li><b>수집 항목</b> 이름, 업체명, 연락처와 선택적으로 입력한 상담 정보</li><li><b>이용 목적</b> 상담 신청 확인, 문의 응대와 서비스 안내</li><li><b>보유 기간</b> 상담 종료 후 1년. 법령상 의무가 있으면 해당 기간 적용</li><li><b>동의 거부</b> 필수 정보 동의를 거부할 수 있으나 상담 접수가 제한됩니다.</li></ul><Link className="button button-ghost" href="/privacy">개인정보처리방침 보기 →</Link></div></section>
 <section className="section section-soft contact-faq"><div className="shell narrow"><div className="section-heading centered"><span className="eyebrow">자주 묻는 질문</span><h2>상담 신청 전에 확인하세요</h2></div><div className="faq-list">{contactFaqs.map(x=><details key={x.q}><summary>{x.q}<span aria-hidden="true">＋</span></summary><p>{x.a}</p></details>)}</div></div></section>
 <section className="contact-direct"><div className="shell"><div><span>직접 연락</span><h2>이메일 상담도 가능합니다</h2><p>확인되지 않은 전화번호·카카오톡·주소·운영시간은 표시하지 않습니다.</p></div><a href="mailto:contact@geosang.co.kr" onClick={()=>trackContactEvent("direct_email_click",{source_page:"/contact",cta_location:"direct_contact"})}>contact@geosang.co.kr →</a></div></section>
 <section className="contact-final"><div className="shell"><span>무료 1:1 상담</span><h2>혼자 고민하지 말고<br/>현재 상황부터 알려주세요</h2><p>지원사업을 찾는 단계인지, 선정 후 실행이 필요한 단계인지 확인한 후 지금 가장 먼저 해야 할 일부터 정리해드립니다.</p><div className="button-row"><a className="button button-light" href="#contact-types">무료 상담 신청</a>{related("무료 자가진단","/diagnosis","final")}{related("선정 후 실행 서비스 보기","/after-selection","final")}</div><small>상담 신청만으로 비용이 발생하거나 계약이 체결되지 않습니다.</small></div></section>
 <nav className="contact-related" aria-label="관련 페이지"><div className="shell">{[["희망리턴패키지","/hope-return"],["정부지원사업","/programs"],["무료 자가진단","/diagnosis"],["선정 후 실행","/after-selection"],["실행 사례","/cases"],["자료실","/insights"],["마케팅 서비스","/services"],["전문가 소개","/experts"],["개인정보처리방침","/privacy"]].map(([label,href])=><Link key={href} href={href} onClick={()=>trackContactEvent("contact_related_page_click",{source_page:"/contact",cta_location:"footer_related"})}>{label} →</Link>)}</div></nav>
 </div>}
