"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { GOOGLE_APPS_SCRIPT_URL, submitConsultation } from "@/lib/contact";
import { trackInsightEvent } from "@/lib/analytics";
import { businessStages, contentTypes, industries, insightCategories, insightFaqs, publishedInsights } from "@/data/insights";
import { InsightCard } from "@/components/InsightCard";

const officialNotice="지원사업의 대상, 지원 내용, 일정과 조건은 해당 연도의 공식 공고를 기준으로 확인하시기 바랍니다.";
const programs=["전체","희망리턴패키지","창업지원사업","소상공인 지원사업","정부지원사업"];
const years=["전체",...Array.from(new Set(publishedInsights.map(x=>x.updatedAt.slice(0,4))))];
const popularTags=["희망리턴패키지","사업계획서","선정 후 실행","홈페이지 제작","결과보고"];

type FilterKey="category"|"stage"|"program"|"industry"|"type"|"year"|"tag";
const filterLabels:Record<FilterKey,string>={category:"카테고리",stage:"사업 단계",program:"지원사업",industry:"업종",type:"유형",year:"연도",tag:"태그"};

function DigitalLibrary(){return <div className="digital-library" aria-label="공고, 체크리스트, 실행 자료를 정리한 디지털 자료실 화면" role="img"><div className="library-window"><div className="window-bar"><i/><i/><i/><span>GEOSANG INSIGHT</span></div><div className="window-grid"><aside><b>자료실</b>{["공고 해설","신청 준비","선정 후 실행","결과보고"].map(x=><span key={x}>{x}</span>)}</aside><main><div className="window-search">무엇을 찾고 계신가요?</div><div className="window-feature"><small>실무 가이드</small><strong>공고부터 실행까지<br/>한눈에 정리</strong></div><div className="window-docs"><span>CHECK</span><span>GUIDE</span><span>REPORT</span></div></main></div></div><div className="floating-note note-one">✓ 공식 출처 확인</div><div className="floating-note note-two">12개 실무 콘텐츠</div></div>}

function Newsletter(){
  const [state,setState]=useState<"idle"|"sending"|"success"|"unavailable"|"error">("idle");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState("sending");const form=e.currentTarget;const fd=new FormData(form);const payload=Object.fromEntries(fd.entries());try{const result=await submitConsultation({...payload,source:"insights-newsletter",requestType:"정보 수신 신청"});if(result.demo||!GOOGLE_APPS_SCRIPT_URL){setState("unavailable");return}setState("success");form.reset();trackInsightEvent("newsletter_form_submit",{cta_location:"insights_newsletter"})}catch{setState("error")}}
  return <section className="section library-newsletter"><div className="shell newsletter-panel"><div><span className="eyebrow light">실무 정보 수신</span><h2>새로운 지원사업과<br/>실무 정보를 받아보세요</h2><p>신규 공고, 희망리턴패키지, 신청 준비와 선정 후 실행 가이드를 정리해 안내합니다.</p><small>정보 수신 동의는 선택이며, 동의하지 않아도 모든 공개 콘텐츠를 볼 수 있습니다.</small></div><form onSubmit={submit}><div className="newsletter-grid"><label>이름<input name="name" required autoComplete="name" placeholder="성함"/></label><label>이메일 또는 연락처<input name="contact" required autoComplete="email" placeholder="name@example.com 또는 010-0000-0000"/></label><label>관심 분야<select name="interest" defaultValue="소상공인"><option>창업지원</option><option>소상공인</option><option>희망리턴패키지</option><option>재창업</option><option>선정 후 실행</option><option>마케팅</option><option>결과보고</option></select></label></div><label className="newsletter-agree"><input type="checkbox" name="privacy" value="동의" required/> <span><Link href="/privacy" target="_blank">개인정보 수집 및 이용</Link>에 동의합니다. (필수)</span></label><label className="newsletter-agree"><input type="checkbox" name="marketing" value="동의"/> <span>새로운 지원사업·마케팅 정보 수신에 동의합니다. (선택)</span></label><button className="button button-coral" disabled={state==="sending"}>{state==="sending"?"신청 중…":"정보 수신 신청"}</button>{state==="success"&&<p className="form-ok" role="status">신청이 접수되었습니다.</p>}{state==="unavailable"&&<p className="form-info" role="status">현재 신청 연결을 준비 중입니다. 공개 콘텐츠는 제한 없이 이용할 수 있습니다.</p>}{state==="error"&&<p className="form-error" role="alert">지금은 신청을 처리할 수 없습니다. 잠시 후 다시 시도해주세요.</p>}</form></div></section>
}

export function InsightsPage(){
  const router=useRouter(),pathname=usePathname(),params=useSearchParams();
  const [query,setQuery]=useState(params.get("q")||"");
  const selected=useMemo(()=>({category:params.get("category")||"전체",stage:params.get("stage")||"전체",program:params.get("program")||"전체",industry:params.get("industry")||"전체 업종",type:params.get("type")||"전체",year:params.get("year")||"전체",tag:params.get("tag")||""}),[params]);
  useEffect(()=>{trackInsightEvent("insights_view")},[]);
  function update(key:FilterKey,value:string){const next=new URLSearchParams(params.toString());if(!value||value==="전체")next.delete(key);else next.set(key,value);router.replace(`${pathname}${next.size?`?${next}`:""}`,{scroll:false});trackInsightEvent("insight_filter_select",{filter_type:key,filter_value:value})}
  function runSearch(e?:FormEvent){e?.preventDefault();const next=new URLSearchParams(params.toString());if(query.trim())next.set("q",query.trim());else next.delete("q");router.replace(`${pathname}${next.size?`?${next}`:""}`,{scroll:false});trackInsightEvent("insight_search",{search_term:query.trim()})}
  function reset(){setQuery("");router.replace(pathname,{scroll:false})}
  const term=(params.get("q")||"").trim().toLocaleLowerCase("ko");
  const results=publishedInsights.filter(item=>{
    const hay=[item.title,item.subtitle,item.description,item.excerpt,item.category,item.subcategory,...item.tags,...item.targetAudience,...item.businessStage,...item.relatedPrograms,...item.industry,...item.content.map(x=>`${x.title} ${x.answer} ${(x.paragraphs||[]).join(" ")} ${(x.bullets||[]).join(" ")}`)].join(" ").toLocaleLowerCase("ko");
    return (!term||hay.includes(term))&&(selected.category==="전체"||item.category===selected.category)&&(selected.stage==="전체"||item.businessStage.includes(selected.stage))&&(selected.program==="전체"||item.relatedPrograms.includes(selected.program))&&(selected.industry==="전체 업종"||item.industry.includes(selected.industry)||item.industry.includes("전체 업종"))&&(selected.type==="전체"||item.contentType===selected.type)&&(selected.year==="전체"||item.updatedAt.startsWith(selected.year))&&(!selected.tag||item.tags.includes(selected.tag));
  });
  const active=(Object.entries(selected) as [FilterKey,string][]).filter(([,v])=>v&&v!=="전체"&&v!=="전체 업종");
  const pre=publishedInsights.filter(x=>x.businessStage.some(s=>["예비창업","초기창업","사업 운영"].includes(s))).slice(0,4);
  const after=publishedInsights.filter(x=>x.businessStage.includes("선정 후 실행")||x.businessStage.includes("결과보고")).slice(0,4);
  const featured=publishedInsights.filter(x=>x.featured).slice(0,3);
  const popular=publishedInsights.filter(x=>x.popular).slice(0,4);
  return <div className="insights-hub">
    <section className="library-hero"><div className="shell library-hero-grid"><div><span className="eyebrow">정부지원사업 실무 자료실</span><h1>신청 전부터 <em>선정 후 실행까지</em><br/>필요한 정보를 쉽게 정리했습니다</h1><p>어려운 공고문과 복잡한 지원 절차를 쉽게 풀고, 선정 이후 홈페이지·콘텐츠·광고와 결과보고까지 안내합니다.</p><form className="hero-search" onSubmit={runSearch} role="search"><label className="sr-only" htmlFor="insight-search">자료 검색</label><input id="insight-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="지원사업명, 신청 준비, 마케팅 또는 결과보고를 검색하세요."/><button aria-label="검색">검색</button></form><div className="suggested-terms"><b>주요 검색어</b>{["희망리턴패키지","정부지원사업 신청","사업계획서","선정 후 실행","홈페이지 제작","결과보고"].map(x=><button key={x} onClick={()=>{setQuery(x);const next=new URLSearchParams(params.toString());next.set("q",x);router.replace(`${pathname}?${next}`,{scroll:false})}}>{x}</button>)}</div><div className="button-row"><a className="button button-primary" href="#all-insights">내게 맞는 자료 찾기</a><Link className="button button-ghost" href="/diagnosis">무료 자가진단 시작</Link><Link className="button button-coral" href="/after-selection#consult">선정 후 실행 상담</Link></div><small>{officialNotice}</small></div><DigitalLibrary/></div></section>

    <section className="section start-guide"><div className="shell"><div className="section-heading"><span className="eyebrow">처음 방문하셨나요?</span><h2>현재 상황에 맞는 정보부터 확인하세요</h2></div><div className="start-guide-grid">{[
      ["01","지원사업을 처음 알아봅니다.",["정부지원사업 찾는 방법","공고문 읽는 방법","신청 자격 확인","무료 자가진단"],"예비창업","처음부터 알아보기"],
      ["02","신청을 준비하고 있습니다.",["신청 서류","사업계획서","평가 기준","자주 하는 실수"],"초기창업","신청 준비 자료 보기"],
      ["03","선정되어 실행을 준비합니다.",["협약서 확인","예산 집행","수행업체 선정","홈페이지·콘텐츠·광고"],"선정 후 실행","선정 후 실행 자료 보기"],
      ["04","결과보고를 준비합니다.",["산출물","증빙","실행 내역","결과보고 자료"],"결과보고","결과보고 자료 보기"],
    ].map(([n,title,items,stage,label])=><button key={String(n)} onClick={()=>{update("stage",String(stage));document.getElementById("all-insights")?.scrollIntoView()}}><span>{n}</span><h3>{title}</h3><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul><b>{label} →</b></button>)}</div></div></section>

    <section className="section section-soft category-overview"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">핵심 카테고리</span><h2>찾는 목적에 따라 빠르게 이동하세요</h2></div><a href="#all-insights" className="text-link">전체 자료 보기 →</a></div><div className="category-grid">{insightCategories.filter(x=>x!=="전체").map(cat=>{const count=publishedInsights.filter(x=>x.category===cat).length;return <button key={cat} onClick={()=>{update("category",cat);document.getElementById("all-insights")?.scrollIntoView()}}><span>{cat}</span><b>{count}개</b><small>{count?"관련 실무 글과 다음 행동을 확인하세요.":"콘텐츠 발행 준비 중"}</small></button>})}</div></div></section>

    <section className="section featured-library"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">추천 콘텐츠</span><h2>처음이라면 이 3개부터 읽어보세요</h2></div><p>신청 전 판단과 선정 후 실행을 이어주는 핵심 글입니다.</p></div><div className="featured-library-grid">{featured.map(x=><InsightCard key={x.slug} item={x} featured/>)}</div></div></section>

    <section className="section section-soft official-guides"><div className="shell"><div className="section-heading"><span className="eyebrow">공식 기준 우선</span><h2>최신 정부지원사업 공고 해설</h2><p>실시간 연동을 가장하지 않습니다. 공식 포털에서 현재 공고를 확인한 뒤 이해하기 쉬운 해설을 제공합니다.</p></div><div className="official-guide-grid">{[
      ["희망리턴패키지","소상공인시장진흥공단·소상공인24","경영위기·폐업·재도전 소상공인","세부 프로그램별 지원","공식 공고 확인","https://www.sbiz24.kr/"],
      ["창업지원사업","중소벤처기업부·K-Startup","예비·초기·도약 단계 창업자","사업화·교육·멘토링 등","공식 공고 확인","https://www.k-startup.go.kr/web/main/index.do"],
      ["기업지원사업","중앙부처·지방자치단체·공공기관","공고별 대상 기업","공고별 지원 분야","일정 확인 필요","https://www.bizinfo.go.kr/"],
    ].map(([name,org,target,support,status,url])=><article key={name}><span>{status}</span><h3>{name}</h3><dl><div><dt>주관기관</dt><dd>{org}</dd></div><div><dt>핵심 대상</dt><dd>{target}</dd></div><div><dt>주요 내용</dt><dd>{support}</dd></div><div><dt>업데이트</dt><dd>세부 공고 기준</dd></div></dl><div><a href={url} target="_blank" rel="noopener noreferrer" onClick={()=>trackInsightEvent("official_source_click",{source_name:String(org)})}>공식 공고 확인 ↗</a><Link href="/insights/notice-reading-order">쉽게 풀어보기 →</Link></div></article>)}</div><p className="official-disclaimer">본 영역은 공고를 쉽게 찾고 이해하기 위한 참고 정보입니다. 최종 신청 대상, 제출 서류, 지원 규모와 일정은 주관기관의 공식 공고를 기준으로 확인하시기 바랍니다.</p></div></section>

    <section className="section journey-library"><div className="shell"><div className="journey-block"><div className="section-heading split"><div><span className="eyebrow">선정 전 준비</span><h2>신청 전에는 무엇을 준비해야 할까요?</h2></div><button className="text-button" onClick={()=>{update("stage","초기창업");document.getElementById("all-insights")?.scrollIntoView()}}>선정 전 자료 전체보기 →</button></div><div className="compact-insight-row">{pre.map(x=><InsightCard key={x.slug} item={x}/>)}</div></div><div className="journey-block after"><div className="section-heading split"><div><span className="eyebrow">선정 후 실행</span><h2>선정 이후에는 어떻게 실행해야 할까요?</h2></div><Link className="button button-coral" href="/after-selection#consult">선정 후 실행 상담</Link></div><div className="compact-insight-row">{after.map(x=><InsightCard key={x.slug} item={x}/>)}</div></div></div></section>

    <section className="section section-soft industry-library"><div className="shell"><div className="section-heading"><span className="eyebrow">업종별 자료</span><h2>업종에 맞는 실행 전략을 확인하세요</h2><p>고객이 찾고 비교하고 문의하는 방식은 업종마다 다릅니다.</p></div><div className="industry-grid">{industries.filter(x=>x!=="전체 업종").map((name,index)=><button key={name} onClick={()=>{update("industry",name);document.getElementById("all-insights")?.scrollIntoView()}}><span>{String(index+1).padStart(2,"0")}</span><b>{name}</b><small>{publishedInsights.some(x=>x.industry.includes(name))?"관련 가이드 보기":"콘텐츠 준비 중"}</small></button>)}</div></div></section>

    <section className="section popular-library"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">인기·추천 자료</span><h2>지금 많이 찾는 실무 주제</h2></div><div className="tag-buttons">{popularTags.map(tag=><button className={selected.tag===tag?"active":""} key={tag} onClick={()=>update("tag",selected.tag===tag?"":tag)}>#{tag}</button>)}</div></div><div className="compact-insight-row">{popular.map(x=><InsightCard key={x.slug} item={x}/>)}</div></div></section>

    <section className="section section-soft all-library" id="all-insights"><div className="shell"><div className="section-heading"><span className="eyebrow">전체 콘텐츠</span><h2>필요한 자료를 검색하고 필터링하세요</h2></div><div className="library-filters"><form className="library-main-search" onSubmit={runSearch}><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="자료 통합 검색" placeholder="제목, 본문, 태그, 지원사업 또는 업종 검색"/><button>검색</button></form><details open className="filter-panel"><summary>필터 열기·접기</summary><div className="library-filter-grid"><label>카테고리<select value={selected.category} onChange={e=>update("category",e.target.value)}>{insightCategories.map(x=><option key={x}>{x}</option>)}</select></label><label>사업 단계<select value={selected.stage} onChange={e=>update("stage",e.target.value)}><option>전체</option>{businessStages.map(x=><option key={x}>{x}</option>)}</select></label><label>지원사업<select value={selected.program} onChange={e=>update("program",e.target.value)}>{programs.map(x=><option key={x}>{x}</option>)}</select></label><label>업종<select value={selected.industry} onChange={e=>update("industry",e.target.value)}>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label>콘텐츠 유형<select value={selected.type} onChange={e=>update("type",e.target.value)}><option>전체</option>{contentTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>업데이트 연도<select value={selected.year} onChange={e=>update("year",e.target.value)}>{years.map(x=><option key={x}>{x}</option>)}</select></label></div></details><div className="filter-status"><b>{results.length}개의 콘텐츠</b><div>{term&&<button onClick={()=>{setQuery("");const next=new URLSearchParams(params.toString());next.delete("q");router.replace(`${pathname}${next.size?`?${next}`:""}`,{scroll:false})}}>검색: {params.get("q")} ×</button>}{active.map(([key,value])=><button key={key} onClick={()=>update(key,"")}>{filterLabels[key]}: {value} ×</button>)}</div>{(term||active.length>0)&&<button className="reset-filters" onClick={reset}>전체 초기화</button>}</div></div>{results.length?<div className="all-library-grid">{results.map(x=><InsightCard key={x.slug} item={x} query={params.get("q")||undefined}/>)}</div>:<div className="library-empty"><span>⌕</span><h3>검색 결과가 없습니다.</h3><p>다른 키워드를 입력하거나 현재 상황을 진단해보세요.</p><div className="button-row"><button className="button button-primary" onClick={reset}>전체 자료 보기</button><Link className="button button-ghost" href="/diagnosis">무료 자가진단</Link><Link className="button button-coral" href="/contact">전문가 상담</Link></div></div>}</div></section>

    <section className="section free-resources"><div className="shell"><div className="section-heading split"><div><span className="eyebrow">무료자료</span><h2>실무에 바로 사용하는 무료자료</h2></div><p>실제 파일이 준비된 자료만 다운로드할 수 있습니다.</p></div><div className="resource-grid">{["정부지원사업 신청 전 체크리스트","희망리턴패키지 준비 체크리스트","선정 후 실행 체크리스트","수행업체 선정 체크리스트","결과보고 산출물 목록","마케팅 실행 계획표"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3><p>대상과 포함 항목, 미리보기를 함께 제공할 예정입니다.</p><button disabled aria-disabled="true">자료 준비 중</button></article>)}</div></div></section>
    <Newsletter/>
    <section className="section section-soft library-faq"><div className="shell narrow"><div className="section-heading centered"><span className="eyebrow">자주 묻는 질문</span><h2>자료실 이용 전에 확인하세요</h2></div><div className="faq-list">{insightFaqs.map(x=><details key={x.q}><summary>{x.q}<span aria-hidden="true">＋</span></summary><p>{x.a}</p></details>)}</div></div></section>
    <section className="library-final"><div className="shell"><div><span>민간 마케팅 전문회사</span><h2>정보를 찾았다면,<br/>내 사업의 다음 행동을 정할 차례입니다</h2><p>현재 상황을 알려주시면 확인할 지원 방향과 선정 후 실행 범위를 함께 정리합니다.</p></div><div className="button-row"><Link className="button button-light" href="/diagnosis">무료 자가진단</Link><Link className="button button-coral" href="/after-selection#consult">선정 후 실행 상담</Link></div></div></section>
  </div>
}
