"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import type { BoardAttachment } from "@/data/board";
export function ResourceDownload({ postId, access, attachments, purpose, items, retention }:{postId:string;access:"public"|"lead"|null;attachments:BoardAttachment[];purpose:string|null;items:string|null;retention:string|null}){
 const [selected,setSelected]=useState(attachments[0]?.id||""),[state,setState]=useState<"idle"|"sending"|"error">("idle"),[message,setMessage]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState("sending");setMessage("");const fd=new FormData(e.currentTarget);const response=await fetch("/api/resources/download",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({postId,attachmentId:selected,name:fd.get("name"),phone:fd.get("phone"),company:fd.get("company"),privacyConsent:fd.get("privacyConsent")==="on",marketingConsent:fd.get("marketingConsent")==="on"})});const result=await response.json().catch(()=>({}));if(!response.ok){setState("error");setMessage(result.message||"다운로드를 준비하지 못했습니다.");return}window.location.assign(result.downloadUrl)}
 if(!attachments.length)return <div className="board-notice"><p>현재 등록된 첨부 자료가 없습니다.</p></div>;
 return <form className="download-form" onSubmit={submit}><h2>첨부 자료 다운로드</h2><label>파일 선택<select value={selected} onChange={e=>setSelected(e.target.value)}>{attachments.map(x=><option value={x.id} key={x.id}>{x.file_name}</option>)}</select></label>{access==="lead"&&<><div className="download-fields"><label>이름<input name="name" maxLength={50} required/></label><label>연락처<input name="phone" inputMode="tel" maxLength={30} required/></label><label>업체명 <small>선택</small><input name="company" maxLength={100}/></label></div><div className="download-policy"><p><b>수집 목적</b> {purpose||"자료 제공 및 신청 내역 확인"}</p><p><b>수집 항목</b> {items||"이름, 연락처, 선택 입력한 업체명"}</p><p><b>보유 기간</b> {retention||"운영 정책 확인 필요"}</p></div><label className="agree"><input name="privacyConsent" type="checkbox" required/> <span><b>필수</b> 개인정보 수집·이용에 동의합니다. <Link href="/privacy" target="_blank">자세히</Link></span></label><label className="agree"><input name="marketingConsent" type="checkbox"/> <span><b>선택</b> 정부지원사업·마케팅 정보 수신에 동의합니다.</span></label></>}<button className="button button-primary" disabled={state==="sending"}>{state==="sending"?"다운로드 준비 중…":"자료 다운로드"}</button>{message&&<p className="form-error" role="alert">{message}</p>}</form>
}
