import type { Metadata } from "next";
import Link from "next/link";
import { listPosts } from "@/lib/boards";
import { newsCategories, recruitmentStatus } from "@/data/board";
import { SITE_NAME } from "@/data/site";
export const metadata: Metadata = { title: "지원사업 소식", description: "공식 출처를 확인한 정부지원사업 모집 정보와 센터 소식을 안내합니다.", alternates: { canonical: "/news" } };
export default async function NewsPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const sp = await searchParams, page = Math.max(1, Number(sp.page) || 1); const result = await listPosts("news", { query: sp.q, category: sp.category, page });
  return <><section className="board-hero"><div className="shell"><span className="eyebrow">공식 정보 확인</span><h1>지원사업 소식</h1><p>모집 정보와 센터 공지를 실제 확인일·공식 링크와 함께 제공합니다.</p></div></section><section className="section"><div className="shell"><form className="board-filter" role="search"><input name="q" defaultValue={sp.q} placeholder="제목과 본문 검색"/><select name="category" defaultValue={sp.category||"전체"}>{newsCategories.map(x=><option key={x}>{x}</option>)}</select><button className="button button-primary">검색</button></form>{!result.configured&&<div className="board-notice"><h2>게시판 연결 준비 중</h2><p>Supabase 운영 프로젝트 연결 후 실제 확인된 소식만 게시됩니다. 임의의 공고나 모집 기간은 표시하지 않습니다.</p></div>}{result.configured&&!result.posts.length&&<div className="board-empty"><h2>게시된 소식이 없습니다.</h2><p>조건을 바꾸거나 나중에 다시 확인해주세요.</p></div>}<div className="board-grid">{result.posts.map(post=>{const status=recruitmentStatus(post);return <article className="board-card" key={post.id}>{post.is_pinned&&<b className="pin">중요</b>}<div className="board-meta"><span>{post.category}</span>{status&&<span className={`recruit ${status==="마감"?"closed":""}`}>{status}</span>}</div><h2><Link href={`/news/${post.slug}`}>{post.title}</Link></h2><p>{post.excerpt}</p><dl><div><dt>주관기관</dt><dd>{post.organization||"본문 확인"}</dd></div>{post.application_end&&<div><dt>마감일</dt><dd>{post.application_end}</dd></div>}<div><dt>정보 확인일</dt><dd>{post.verified_at||"본문 확인"}</dd></div></dl><Link className="text-link" href={`/news/${post.slug}`}>자세히 보기 →</Link></article>})}</div><nav className="pagination" aria-label="페이지 이동">{page>1&&<Link href={`/news?page=${page-1}`}>← 이전</Link>}<span>{page} 페이지</span>{result.hasMore&&<Link href={`/news?page=${page+1}`}>다음 →</Link>}</nav></div></section></>;
}
