import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createSignedUrl, getAuthContext, supabaseRequest } from "@/lib/supabase";
import { projectStageLabels } from "@/data/board";
import { ProjectActions } from "@/components/ProjectActions";
export const metadata:Metadata={title:"프로젝트 진행 현황",robots:{index:false,follow:false}};
type Project={id:string;name:string;service_scope:string;stage:string;schedule_start:string|null;schedule_end:string|null;requests:string;project_comments:Array<{id:string;body:string;created_at:string}>;revision_requests:Array<{id:string;body:string;status:string;admin_reply:string;created_at:string}>;project_files:Array<{id:string;object_path:string;file_name:string;file_kind:string;created_at:string}>};
export default async function ProjectPage({params}:{params:Promise<{id:string}>}){const auth=await getAuthContext();const {id}=await params;if(!auth)redirect(`/login?next=/portal/${encodeURIComponent(id)}`);const rows=await supabaseRequest<Project[]>(`/rest/v1/projects?id=eq.${encodeURIComponent(id)}&select=*,project_comments(id,body,created_at),revision_requests(id,body,status,admin_reply,created_at),project_files(id,object_path,file_name,file_kind,created_at)&limit=1`,{token:auth.accessToken}).catch(()=>[]);const project=rows[0];if(!project)notFound();const files=await Promise.all((project.project_files||[]).map(async f=>({...f,url:await createSignedUrl("project-files",f.object_path,300).catch(()=>"")})));return <section className="private-shell wide project-detail"><Link href="/portal">← 프로젝트 목록</Link><header><span>{projectStageLabels[project.stage]||project.stage}</span><h1>{project.name}</h1><p>{project.service_scope}</p></header><div className="project-summary"><div><b>진행 단계</b><span>{projectStageLabels[project.stage]}</span></div><div><b>예정 일정</b><span>{project.schedule_start||"협의 중"} ~ {project.schedule_end||"협의 중"}</span></div><div><b>요청 사항</b><span>{project.requests||"등록된 요청 사항이 없습니다."}</span></div></div><section><h2>첨부파일</h2>{files.length?<ul>{files.map(f=><li key={f.id}><span>{f.file_kind}</span>{f.url?<a href={f.url}>{f.file_name}</a>:f.file_name}<small>{f.created_at.slice(0,10)}</small></li>)}</ul>:<p>등록된 파일이 없습니다.</p>}</section><section><h2>수정 요청</h2>{project.revision_requests?.length?<ul>{project.revision_requests.map(x=><li key={x.id}><b>{x.status}</b><p>{x.body}</p>{x.admin_reply&&<blockquote>관리자 답변: {x.admin_reply}</blockquote>}</li>)}</ul>:<p>등록된 수정 요청이 없습니다.</p>}</section><section><h2>댓글과 변경 기록</h2>{project.project_comments?.length?<ul>{project.project_comments.map(x=><li key={x.id}><p>{x.body}</p><small>{new Date(x.created_at).toLocaleString("ko-KR")}</small></li>)}</ul>:<p>등록된 댓글이 없습니다.</p>}</section><ProjectActions projectId={project.id}/></section>}
